map_memory_node:
  ros__parameters:
    local_costmap_topic: "/costmap" 
    odom_topic: "/odom/filtered" 
    map_topic: "/map" 


    map_pub_rate: 3000
    update_distance: 1.5

    global_map:
      resolution: 0.5
      width: 60
      height: 60

      origin:
        position:
          x: -15.0 
          y: -15.0 # given by -1 * height * resolution / 2
        orientation:
          w: 1.0