costmap_node:
  ros__parameters:
    resolution: 0.10 
    width: 300
    height: 300
    
    origin:
      x: -15.0 
    
      y: -15.0 

      orientation: 
        w: 1.0
    
    inflation_radius: 1.5

    #these probably fine tweak later if buns
      