costmap_node:
  ros__parameters:
    resolution: 0.40 
    width: 120
    height: 120
    
    origin:
      x: -24.0 
    
      y: -24.0 

      orientation: 
        w: 1.0
    
    inflation_radius: 1.50

    #these probably fine tweak later if buns
      